[mtg]
src.github = "9seconds/mtg"
fetch.github = "9seconds/mtg"
git.fetchSubmodules = true

[sing-box]
src.github = "SagerNet/sing-box"
fetch.github = "SagerNet/sing-box"
git.fetchSubmodules = true

[xray]
src.github = "XTLS/Xray-core"
fetch.github = "XTLS/Xray-core"
git.fetchSubmodules = true

[clash-meta]
src.github = "MetaCubeX/Clash.Meta"
fetch.github = "MetaCubeX/Clash.Meta"
git.fetchSubmodules = true

[clash-premium]
src.webpage = "https://github.com/Dreamacro/clash/releases/tag/premium"
src.regex = "Premium ([0-9\\.]*)"
fetch.url = "https://github.com/Dreamacro/clash/releases/download/premium/clash-linux-amd64-$ver.gz"
