[mtg]
src.github = "9seconds/mtg"
fetch.github = "9seconds/mtg"
git.fetchSubmodules = true

[sing-box]
src.github = "SagerNet/sing-box"
fetch.github = "SagerNet/sing-box"
git.fetchSubmodules = true

[xray]
src.github = "XTLS/Xray-core"
fetch.github = "XTLS/Xray-core"
git.fetchSubmodules = true

[clash-meta]
src.github = "MetaCubeX/Clash.Meta"
fetch.github = "MetaCubeX/Clash.Meta"
git.fetchSubmodules = true

[clash-premium]
src.webpage = "https://github.com/zhongfly/Clash-premium-backup/tags/"
src.regex = "\\d{4}-\\d{2}-\\d{2}-[a-z0-9]{8}"
fetch.url = "https://github.com/zhongfly/Clash-premium-backup/releases/download/$ver/clash-linux-amd64-n$ver.gz"
