# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  clash-meta = {
    pname = "clash-meta";
    version = "v1.14.2";
    src = fetchFromGitHub ({
      owner = "MetaCubeX";
      repo = "Clash.Meta";
      rev = "v1.14.2";
      fetchSubmodules = true;
      sha256 = "sha256-sn+0TNXCK4af4zfkf09hLsFkuvkcyjhwh35kKo993FQ=";
    });
  };
  clash-premium = {
    pname = "clash-premium";
    version = "2023.03.04";
    src = fetchurl {
      url = "https://github.com/Dreamacro/clash/releases/download/premium/clash-linux-amd64-2023.03.04.gz";
      sha256 = "sha256-BO+TtKTDvJYnLqRx/SZZFMz0o4QSEP4xKUqMlZotq8g=";
    };
  };
  mtg = {
    pname = "mtg";
    version = "v2.1.7";
    src = fetchFromGitHub ({
      owner = "9seconds";
      repo = "mtg";
      rev = "v2.1.7";
      fetchSubmodules = true;
      sha256 = "sha256-7AJeiTyss/PlIMkTcCIwFrEmRIQYjleUXDUqjYfj/PM=";
    });
  };
  sing-box = {
    pname = "sing-box";
    version = "v1.1.7";
    src = fetchFromGitHub ({
      owner = "SagerNet";
      repo = "sing-box";
      rev = "v1.1.7";
      fetchSubmodules = true;
      sha256 = "sha256-jovUK535vZeCgnnW+9/gjXwCkNLMXdiCJwWqFKCubcU=";
    });
  };
  xray = {
    pname = "xray";
    version = "v1.7.5";
    src = fetchFromGitHub ({
      owner = "XTLS";
      repo = "Xray-core";
      rev = "v1.7.5";
      fetchSubmodules = true;
      sha256 = "sha256-WCku/7eczcsGiIuTy0sSQKUKXlH14TpdVg2/ZPdaiHQ=";
    });
  };
}
